### ISSUE TITLE
mob ai broken

### ISSUE THREAD

**Issue by freopt** [ldtteam/PerViamInvenire#15] opened 2022-02-04 21:43 UTC
1.18.1 lateset version

https://user-images.githubusercontent.com/45438411/152606975-09729de2-8ac9-4dbe-9052-3cb43dcb7b81.mp4

**Comment by LDexter** [comment] 2022-06-19 14:05
OH MY. I've been digging through my list of >100 in a custom mod pack for the longest time, thank you for making the connection I needed!!

**Comment by YassaaaTU** [comment] 2022-06-21 11:32
yea the issue is still there btw :/

but unlike the video you posted entities really just keep spinning in their place the whole time

**Comment by marchermans** [comment] 2022-09-17 13:27
Should be fixed in both the latest 1.18.2 as well as the new 1.19

**Comment by marchermans** [comment] 2023-05-28 12:35
Fixed in the latest 1.19.x releases.
Sadly I won't be backporting this.

**Closed as completed by marchermans** 2023-05-28 12:35 UTC
